# fly.toml app configuration file generated for shy-brook-4156 on 2023-10-18T19:38:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shy-brook-4156"
primary_region = "ord"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
